"""add join_model to Enrollment

Revision ID: 8741313faa9c
Revises: 59f13898d3e9
Create Date: 2024-05-22 17:15:12.826716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8741313faa9c'
down_revision = '59f13898d3e9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enrollment', sa.Column('join_model', sa.Enum('RESTRICTED', 'OPEN', 'AUTO', 'CLOSED', 'REMOVED', name='joinmodel'), server_default='AUTO', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enrollment', 'join_model')
    # ### end Alembic commands ###
