"""add json_data to Group

Revision ID: 59f13898d3e9
Revises: 307f9c387c90
Create Date: 2024-05-01 19:27:18.028782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59f13898d3e9'
down_revision = '307f9c387c90'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('json_data', sa.JSON(), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group', 'json_data')
    # ### end Alembic commands ###
