"""use paths instead of ids for gitlab projects

Revision ID: b5a2c82718b8
Revises: 9edd20cea125
Create Date: 2024-10-25 01:40:31.583231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5a2c82718b8'
down_revision = '9edd20cea125'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignment', sa.Column('gitlab_path', sa.String(), nullable=True))
    op.add_column('assignment', sa.Column('gitlab_root_path', sa.String(), nullable=True))
    op.add_column('assignment', sa.Column('gitlab_test_path', sa.String(), nullable=True))
    op.drop_column('assignment', 'gitlab_root_id')
    op.drop_column('assignment', 'gitlab_test_id')
    op.drop_column('assignment', 'gitlab_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignment', sa.Column('gitlab_id', sa.INTEGER(), nullable=True))
    op.add_column('assignment', sa.Column('gitlab_test_id', sa.INTEGER(), nullable=True))
    op.add_column('assignment', sa.Column('gitlab_root_id', sa.INTEGER(), nullable=True))
    op.drop_column('assignment', 'gitlab_test_path')
    op.drop_column('assignment', 'gitlab_root_path')
    op.drop_column('assignment', 'gitlab_path')
    # ### end Alembic commands ###
